services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      DB_CONN: Host=db;Database=appdb;Username=appuser;Password=apppassword
    depends_on:
      - db
